on:
  workflow_call: {}

name: "Documentation"

permissions:
  contents: read

jobs:
  generate:
    name: "Generate"

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: .tool-versions
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: _build
          key: docs-build-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            docs-build-{{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - uses: actions/cache@v4
        with:
          path: deps
          key: docs-deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('rebar.config') }}
          restore-keys: |
            docs-bdepsuild-{{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - run: mix docs

      - name: "Create Docs Archive"
        run: |
          tar -czvf docs.tar.gz doc
      
      - name: "Attest docs provenance"
        uses: actions/attest-build-provenance@v1
        id: attest-docs-provenance
        with:
          subject-path: 'docs.tar.gz'
      - name: "Copy docs provenance"
        run: cp "$ATTESTATION" docs.tar.gz.sigstore
        env:
          ATTESTATION: "${{ steps.attest-docs-provenance.outputs.bundle-path }}"

      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs.tar.gz*
